# Generated by Django 5.1.5 on 2025-03-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
        migrations.AddField(
            model_name='otp',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
