# Generated by Django 5.1.5 on 2025-03-28 19:45

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_otp_email_otp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_id',
            field=models.CharField(default=accounts.models.Wallet.generate_wallet_id, max_length=50, unique=True),
        ),
    ]
