# Generated by Django 5.1.5 on 2025-04-02 17:02

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 17, 2, 8, 937240, tzinfo=datetime.timezone.utc)),
        ),
    ]
