# Generated by Django 5.1.5 on 2025-05-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='can_create_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='can_create_service',
            field=models.BooleanField(default=False),
        ),
    ]
