# Generated by Django 5.0.6 on 2026-05-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subscriptionpackage_can_create_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='max_products',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='max_services',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
