from django.urls import path

import apis.views as views

app_name = 'apis'
urlpatterns = [
    path('', views.HealthCheckAPIView.as_view(), name='ping'),
]

# accounts and users
urlpatterns += [
    path('homepage/', views.HomepageAPIView.as_view(), name='homepage'),
    path('login/', views.LoginAPI.as_view(), name='login'),
    path('verifyotp/', views.VerifyOTPAPI.as_view(), name='verify_otp'),
    path('register/', views.RegisterAPI.as_view(), name='register_user'),
    path('userprofile/', views.UserProfileAPIView.as_view(), name='profile'),
    path('userprofile/avatar/', views.UserProfileAvatarAPIView.as_view(), name='profile_avatar_update'),
    path('changepassword/', views.ChangePasswordAPIView.as_view(), name='change_password'), 
    path('resetpassword/', views.ResetPasswordAPIView.as_view(), name='reset_password'),
    path('users/', views.UsersAPIView.as_view(), name='users'),
    path('services/', views.ServicesAPIView.as_view(), name='services'),
    path('bookings/', views.BookingsAPIView.as_view(), name='bookings'),
    path('vendors/', views.VendorsAPIView.as_view(), name='vendors'),
    path('vendorprofile/', views.VendorProfileAPIView.as_view(), name='vendorprofile'),
    path('subscriptionpackage/', views.SubscriptionPackageAPIView.as_view(), name='sub_package'),
    path('subscriptions/', views.SubscriptionAPIView.as_view(), name='subscriptions'),
    path('renewsubscription/', views.SubscriptionRenewalAPIView.as_view(), name='renewsubscription'),
    path('dashboard/', views.DashboardAPIView.as_view(), name='dashboard'),
    path('products/', views.ProductAPIView.as_view(), name='products'),
    path('products/<int:product_id>/images/', views.ProductExtraImagesAPIView.as_view(), name='product_extra_images'),
    path('products/<int:product_id>/images/<int:image_id>/', views.ProductExtraImagesAPIView.as_view(), name='product_extra_image_detail'),
    path('services/<int:service_id>/images/', views.ServiceExtraImagesAPIView.as_view(), name='service_extra_images'),
    path('services/<int:service_id>/images/<int:image_id>/', views.ServiceExtraImagesAPIView.as_view(), name='service_extra_image_detail'),
    path('productcategory/', views.ProductCategoryAPIView.as_view(), name='category'),
    path('placeorder/', views.PlaceOrderAPIView.as_view(), name='place_order'),
    path('orders/', views.OrderAPIView.as_view(), name='orders'),
    path('customerproducts/', views.CustomerProductsAPIView.as_view(), name='customer_products'),
    path('customerservices/', views.CustomerServicesAPIView.as_view(), name='customer_services'),
    path('searchproducts/', views.ProductSearchAPIView.as_view(), name='search'),
    path('productratings/', views.ProductRatingsAPIView.as_view(), name='product_ratings'),
    path('cashout/', views.VendorCashoutAPI.as_view(), name='cashout'),
    path('cashout/paystack/', views.PaystackCashoutInitiateAPI.as_view(), name='cashout_paystack'),
    path('cashout/paystack/finalize/', views.PaystackCashoutFinalizeAPI.as_view(), name='cashout_paystack_finalize'),
    path('cashout/paystack/verify/', views.PaystackCashoutVerifyAPI.as_view(), name='cashout_paystack_verify'),
    path('payments/', views.PaymentAPIView.as_view(), name='payments'),
    path('makepayment/', views.MakePaymentAPI.as_view(), name='make_payment'),
    path('makepayment/paystack/', views.MakePaystackPaymentAPI.as_view(), name='make_payment_paystack'),
    path('paymentcallback/', views.PaymentCallbackAPI.as_view(), name='payment_callback'),
    path('paymentstatus/', views.PaymentStatusCheckAPI.as_view(), name='payment_status'),
    path('paystack/verify/', views.PaystackVerifyAPI.as_view(), name='paystack_verify'),
    path('paystack/status/', views.PaystackVerifyAPI.as_view(), name='paystack_status'),
    path('paystack/webhook/', views.PaystackWebhookAPI.as_view(), name='paystack_webhook'),
    path('paystack/banks/', views.PaystackBanksAPIView.as_view(), name='paystack_banks'),
    path('telcos/', views.PaystackTelcosAPIView.as_view(), name='telcos'),
    path('banks/', views.PaystackSupportedBanksAPIView.as_view(), name='banks'),
    path('payouts/', views.PayoutsAPIView.as_view(), name='payouts'),
    path('payouts/approve/', views.ApprovePayoutAPIView.as_view(), name='payouts_approve'),
    path('payouts/approve-all/', views.ApproveAllPendingPayoutsAPIView.as_view(), name='payouts_approve_all'),
    path('banners/', views.BannerAPIView.as_view(), name='banners'),
    path('videoads/', views.VideoAdAPIView.as_view(), name='video_ads'),
    path('locations/', views.LocationsAPIView.as_view(), name='locations'),
    path('deliveryfees/', views.DeliveryFeesAPIView.as_view(), name='delivery_fees'),
    path('servicefees/', views.ServiceFeesAPIView.as_view(), name='service_fees'),
]