# Generated by Django 5.1.5 on 2025-04-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
