# Generated by Django 5.1.5 on 2025-04-17 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_subscription_start_date'),
        ('apis', '0007_banner_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.vendor'),
        ),
    ]
