# Generated by Django 5.1.5 on 2025-05-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_payment_payment_type_payment_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='discout_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], default='Percentage', max_length=50),
        ),
    ]
