# Generated by Django 5.1.5 on 2025-05-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_ad_discout_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='discout_type',
            new_name='discount_type',
        ),
    ]
