# Generated by Django 5.1.5 on 2025-05-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_rename_discout_type_ad_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vendor_credited_debited',
            field=models.BooleanField(default=False),
        ),
    ]
