# Generated by Django 5.1.5 on 2025-05-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_payment_vendor_credited_debited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
