# Generated by Django 5.1.5 on 2025-05-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
