# Generated by Django 5.1.5 on 2025-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_alter_servicebooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
