# Generated by Django 5.1.5 on 2026-01-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_service_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MOMO', 'MOMO'), ('CASH', 'CASH'), ('PAYSTACK', 'PAYSTACK')], default='MOMO', max_length=10),
        ),
    ]
