# Generated by Django 5.2.7 on 2026-02-18 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subscriptionpackage_can_create_product_and_more'),
        ('apis', '0021_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(default='PENDING', max_length=10)),
                ('payout_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='apis.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='apis.payment')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='accounts.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_items', to='apis.orderitem')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apis.payout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_items', to='apis.product')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(fields=('order', 'vendor'), name='unique_payout_per_order_vendor'),
        ),
        migrations.AddConstraint(
            model_name='payoutitem',
            constraint=models.UniqueConstraint(fields=('payout', 'order_item'), name='unique_payout_item_per_order_item'),
        ),
    ]
