# Generated by Django 5.2.7 on 2026-02-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_settled_by_if_missing(apps, schema_editor):
    """Add Payout.settled_by column only if it doesn't already exist.

    Some environments may already have the column (e.g., applied from a different
    migration set or manual schema change). SQLite will error on duplicate column
    names, so we guard it here.
    """

    Payout = apps.get_model('apis', 'Payout')
    table_name = Payout._meta.db_table
    column_name = 'settled_by_id'

    with schema_editor.connection.cursor() as cursor:
        existing_columns = {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if column_name in existing_columns:
        return

    # NOTE: The historical Payout model at this point (dependency 0022) may not
    # yet include the `settled_by` field in its state, so we define the field
    # explicitly for the database operation.
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    UserModel = apps.get_model(user_app_label, user_model_name)

    field = models.ForeignKey(
        to=UserModel,
        on_delete=django.db.models.deletion.SET_NULL,
        null=True,
        blank=True,
        related_name='settled_payouts',
    )
    field.set_attributes_from_name('settled_by')
    schema_editor.add_field(Payout, field)


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_payout_payoutitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.FileField(upload_to='video_ads/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_settled_by_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='payout',
                    name='settled_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_payouts', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name='UserVideoAdState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_shown_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_ad_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
