# Generated by Django 5.2.7 on 2026-02-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_videoad_payout_settled_by_uservideoadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
