# Generated by Django 5.1.5 on 2026-02-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_product_available_colors_product_available_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
