# Generated by Django 5.1.5 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0031_remove_order_delivery_location_alter_order_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription_effects_applied',
            field=models.BooleanField(default=False),
        ),
    ]
