# Generated by Django 5.1.5 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0032_payment_subscription_effects_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(db_index=True, max_length=255)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['reference', 'processed'], name='apis_paysta_referen_8d01a6_idx')],
            },
        ),
    ]
