# Generated by Django 5.1.5 on 2026-02-21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0033_paystackwebhookevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paystackwebhookevent',
            old_name='apis_paysta_referen_8d01a6_idx',
            new_name='apis_paysta_referen_b8ae49_idx',
        ),
    ]
