# Generated by Django 5.1.5 on 2026-03-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0038_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='other_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
