# Generated by Django 5.1.5 on 2026-03-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0039_order_other_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('DEPARTMENT', 'Department'), ('HALL', 'Hall'), ('HOSTEL', 'Hostel'), ('OFF CAMPUS', 'Off Campus'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
