# Generated by Django 5.1.5 on 2026-03-22 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


def generate_refund_reference():
    return uuid.uuid4().hex


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_subscriptionpackage_can_create_product_and_more'),
        ('apis', '0040_order_service_fee_amount_alter_location_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refunded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(default='mobile_money', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('provider_code', models.CharField(max_length=50)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(db_index=True, default=generate_refund_reference, editable=False, max_length=255, unique=True)),
                ('recipient_code', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_code', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='PENDING', max_length=10)),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='apis.payment')),
                ('refunded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_issued', to='accounts.user')),
            ],
        ),
    ]
