# Generated by Django 5.1.5 on 2026-03-23 22:43

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0041_refund_and_payment_refunded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='reference',
            field=models.CharField(db_index=True, default=apis.models.Refund.generate_reference, editable=False, max_length=255, unique=True),
        ),
    ]
