# Generated by Django 5.1.5 on 2026-04-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0042_alter_refund_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='other_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
