# Generated by Django 5.0.6 on 2026-06-05 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_subscriptionpackage_max_products_and_more'),
        ('apis', '0044_product_stock_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='VendorCustomerCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed amount')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_redemptions', models.PositiveIntegerField(default=1)),
                ('per_customer_limit', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_coupons', to='accounts.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='applied_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='apis.vendorcustomercoupon'),
        ),
        migrations.CreateModel(
            name='VendorCustomerCouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='apis.vendorcustomercoupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_coupon_redemptions', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='apis.order')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPublishingCreditCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('credit_type', models.CharField(choices=[('PRODUCT', 'Product credits'), ('SERVICE', 'Service credits'), ('BOTH', 'Product and service credits')], default='BOTH', max_length=20)),
                ('product_credits', models.PositiveIntegerField(default=0)),
                ('service_credits', models.PositiveIntegerField(default=0)),
                ('max_redemptions', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_publishing_credit_coupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorPublishingCreditRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_credits', models.PositiveIntegerField(default=0)),
                ('service_credits', models.PositiveIntegerField(default=0)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='apis.vendorpublishingcreditcoupon')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishing_credit_redemptions', to='accounts.vendor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vendorcustomercoupon',
            constraint=models.UniqueConstraint(fields=('vendor', 'code'), name='unique_customer_coupon_code_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='vendorpublishingcreditredemption',
            constraint=models.UniqueConstraint(fields=('vendor', 'coupon'), name='unique_vendor_publishing_coupon_redemption'),
        ),
    ]
