
name: BIRTHNON CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
env:
  PYTHON_VERSION: '3.12.7'
  DJANGO_SETTINGS_MODULE: 'bscore.settings.test'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bscore/requirements.txt
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        
    - name: Run migrations
      run: python manage.py migrate
        
    - name: Run tests
      run: python manage.py test

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bscore/requirements.txt
        
    - name: Collect static files
      run: python manage.py collectstatic --noinput
      
    - name: Install sshpass for password authentication
      run: sudo apt-get install -y sshpass
      
    - name: Deploy to DigitalOcean
      run: |
        sshpass -p "${{ secrets.DO_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
        ${{ secrets.DO_USERNAME || 'root' }}@${{ secrets.DO_HOST }} \
        "python3 deploy_django.py"
